export const PRODUCTS_ACTION = {
  GET_PRODUCTS_REQUEST: "PRODUCTS/GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "PRODUCTS/GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILED: "PRODUCTS/GET_PRODUCTS_FAILED",

  GET_ONE_PRODUCT_REQUEST: "PRODUCTS/GET_ONE_PRODUCT_REQUEST",
  GET_ONE_PRODUCT_SUCCESS: "PRODUCTS/GET_ONE_PRODUCT_SUCCESS",
  GET_ONE_PRODUCT_FAILED: "PRODUCTS/GET_ONE_PRODUCT_FAILED",

  CART_REQUEST: "PRODUCTS/CART_REQUEST",
  CART_SUCCESS: "PRODUCTS/CART_SUCCESS",
  CART_FAILED: "PRODUCTS/CART_FAILED",

  ADD_TO_CART_REQUEST: "PRODUCTS/ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "PRODUCTS/ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILED: "PRODUCTS/ADD_TO_CART_FAILED",

  REMOVE_FROM_CART_REQUEST: "PRODUCTS/REMOVE_FROM_CART_REQUEST",
  REMOVE_FROM_CART_SUCCESS: "PRODUCTS/REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_FAILED: "PRODUCTS/REMOVE_FROM_CART_FAILED",

  ADD_CATEGORY_REQUEST: "PRODUCTS/ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "PRODUCTS/ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILED: "PRODUCTS/ADD_CATEGORY_FAILED",

  USER_ORDERS_REQUEST: "PRODUCTS/USER_ORDERS_REQUEST",
  USER_ORDERS_SUCCESS: "PRODUCTS/USER_ORDERS_SUCCESS",
  USER_ORDERS_FAILED: "PRODUCTS/USER_ORDERS_FAILED",

  GET_CATEGORY_REQUEST: "PRODUCTS/GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "PRODUCTS/GET_CATEGORY_SUCCESS",
  GET_CATEGORY_FAILED: "PRODUCTS/GET_CATEGORY_FAILED",

  SET_SEARCH_CATEGORY: "PRODUCTS/SET_SEARCH_CATEGORY",

  ADD_PRODUCT_REQUEST: "PRODUCTS/ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "PRODUCTS/ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILED: "PRODUCTS/ADD_PRODUCT_FAILED",

  PLACE_ORDER_REQUEST: "PRODUCTS/PLACE_ORDER_REQUEST",
  PLACE_ORDER_SUCCESS: "PRODUCTS/PLACE_ORDER_SUCCESS",
  PLACE_ORDER_FAILED: "PRODUCTS/PLACE_ORDER_FAILED",

  GET_ORDER_REQUEST: "PRODUCTS/GET_ORDER_REQUEST",
  GET_ORDER_SUCCESS: "PRODUCTS/GET_ORDER_SUCCESS",
  GET_ORDER_FAILED: "PRODUCTS/GET_ORDER_FAILED",

  CONTACT_US_REQUEST: "PRODUCTS/CONTACT_US_REQUEST",
  CONTACT_US_SUCCESS: "PRODUCTS/CONTACT_US_SUCCESS",
  CONTACT_US_FAILED: "PRODUCTS/CONTACT_US_FAILED",

  POST_REVIEW_REQUEST: "PRODUCTS/POST_REVIEW_REQUEST",
  POST_REVIEW_SUCCESS: "PRODUCTS/POST_REVIEW_SUCCESS",
  POST_REVIEW_FAILED: "PRODUCTS/POST_REVIEW_FAILED",

  GET_REVIEWS_REQUEST: "PRODUCTS/GET_REVIEWS_REQUEST",
  GET_REVIEWS_SUCCESS: "PRODUCTS/GET_REVIEWS_SUCCESS",
  GET_REVIEWS_FAILED: "PRODUCTS/GET_REVIEWS_FAILED",

  GET_USER_REQUEST: "PRODUCTS/GET_USER_REQUEST",
  GET_USER_SUCCESS: "PRODUCTS/GET_USER_SUCCESS",
  GET_USER_FAILED: "PRODUCTS/GET_USER_FAILED",

  UPDATE_ORDER_ADMIN_REQUEST: "PRODUCTS/UPDATE_ORDER_ADMIN_REQUEST",
  UPDATE_ORDER_ADMIN_SUCCESS: "PRODUCTS/UPDATE_ORDER_ADMIN_SUCCESS",
  UPDATE_ORDER_ADMIN_FAILED: "PRODUCTS/UPDATE_ORDER_ADMIN_FAILED",

  UPDATE_USER_REQUEST: "PRODUCTS/UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "PRODUCTS/UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "PRODUCTS/UPDATE_USER_FAILED",

  DELETE_ACCOUNT_REQUEST: "PRODUCTS/DELETE_ACCOUNT_REQUEST",
  DELETE_ACCOUNT_SUCCESS: "PRODUCTS/DELETE_ACCOUNT_SUCCESS",
  DELETE_ACCOUNT_FAILED: "PRODUCTS/DELETE_ACCOUNT_FAILED",
};

export const LOGIN_ACTIONS = {
  LOGIN_REQUEST: "LOGIN/LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN/LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN/LOGIN_FAILED",

  SET_LOGIN: "LOGIN/SET_LOGIN",
};
